### ISSUE TITLE
Further tweaking

### ISSUE THREAD

**Issue by scoob8000** [hn/reolink-camera#1]
Soon as I get some time I want to play around with this.   I have this camera with the same firmware, but the recording options are crippled.   One can only use VBR vs CBR and cannot set the keyframe rate.

I'm led to believe the RLC-420-5MP uses the same hardware, but has these options exposed in the web interface.   I've tried flashing the firmware directly but it fails.  Suspecting there is some sort of check before flashing.

Just wanted to reach out in case you've already encountered this.

Thank you for your work!

**Comment by hn** [comment]
Hi, I do not have access to RLC-420-5MP hardware and I didn't have time to read any specs about this device so far.

From a quick view see almost no differences between the firmware files:
```
$ diff -r RLC-410-5MP_448_19061407/rootfs/ RLC-420-5MP_448_19061408/rootfs/ 2>/dev/null
diff -r RLC-410-5MP_448_19061407/rootfs/mnt/app/dvr.xml RLC-420-5MP_448_19061408/rootfs/mnt/app/dvr.xml
7c7
< display_type_info="RLC-410-5MP"
---
> display_type_info="RLC-420-5MP"
13c13
< build_index="07"
---
> build_index="08"
59c59
< ipc_mirror="0"
---
> ipc_mirror="1"
61c61
< ipc_flip="0"
---
> ipc_flip="1"
diff -r RLC-410-5MP_448_19061407/rootfs/mnt/app/version_file RLC-420-5MP_448_19061408/rootfs/mnt/app/version_file
1c1
< 448_19061407
---
> 448_19061408
```

That does not necessarily mean that the hardware is identical! Some hardware infos and settings are stored in  the non-linux part of the firmware and the linux firmware has lots of switches `(if $SENSOR == ...)`.

Please report back if you have any new findings.

**Comment by hn** [comment]
Maybe a good place to start is to compare the GUI code and see where those CBR/VBR/keyframe switches are located:

```
$ ls RLC-420-5MP_448_19061408/rootfs/mnt/app/www/htmls/ -1
cfg-alarm-motion-audio.html
cfg-alarm-motion-detect.html
cfg-alarm-motion-general.html
cfg-alarm-motion-sensitivity.html
cfg-cloud-account.html
cfg-device-hdd.html
cfg-display-camera-osd.html
cfg-log-search.html
cfg-network-advanced-ddns.html
...
```
