### ISSUE TITLE
How to reflash entire firmware?

### ISSUE THREAD

**Issue by Zipdox2** [hn/reolink-camera#12]
I think I semi-bricked my device with a stock firmware upgrade. It won't connect to the network anymore and I think it's boot looping. Uboot seems to be intact and the serial console works. How would I reflash the entire stock firmware?

**Comment by hn** [comment]
Set up ethernet within U-boot, then tftp-transfer files to RAM and write them to the correct position of the flash ("sf" commands). Don't remember if I ever did that, but it should be doable, at least what the docs say; https://github.com/hn/reolink-camera/blob/master/log-u-boot.txt
