### ISSUE TITLE
Unable to make the buildroot

### ISSUE THREAD

**Issue by pborges** [hn/reolink-camera#2]
First off thank you for doing this, I have a ton of these cameras and their unwillingness to ditch the flash player is making me want to take the issue into my own hands, however, I have never done much with embedded Linux (though I am not a stranger to embedded programming) and could use some pointers if you have the time,

So far I have been unable to make the buildroot environment,

```freadahead.c: In function 'freadahead':
freadahead.c:91:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   91 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
      |   ^~~~~
fseeko.c: In function 'rpl_fseeko':
fseeko.c:109:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
  109 |   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
      |    ^~~~~
``` 
I believe this has to do with my development system having a newer version of glibc, have you encountered this issue? If so, how did you work around it, if not, what OS and version are you using?

Also, if you happen to know of a quick tutorial on compiling/including a custom binary in a buildroot environment that would be amazing!

I am not sure I need that to get an html5 video player working on this camera but it would be nice to know how to do that.

Thank you!

**Comment by hn** [comment]
Sorry I can't help you with buildroot, I think the Buildroot community/forum is a better place to search/ask for questions. I'm using Debian Buster and Buildroot worked out of the Box for me. I suggest to use containers/VMs for develepment, that makes many things easier and you're not polluting your very own systems with all that unstable/experimental stuff.

The camera offers RTMP and RTSP streams. I _think_ RTMP isn't compatible with HTML5, for RTSP there [might be options](https://github.com/Streamedian/html5_rtsp_player). Maybe you do not need to compile any binaries. I _might_ be enough to patch the webcam's HTML source code to include some fance RTSP player. But that's just a guess.

Please report any progress you make, it might be interesting for other people.

**Comment by pborges** [comment]
Thanks, I was going to spin up a VM just didn't know how old I had to go. Only reason I wanted to make the buildroot was to add ffmpeg, i didn't see it in the existing image, and it may be required, I am going to try just modifying the html first. I will keep you appraised! Thank you.
