### ISSUE TITLE
argus 2

### ISSUE THREAD

**Issue by user747** [hn/reolink-camera#3]
hey thanks for the guide. noticed argus 2 has 5 pin UART. seems to be based on a Grain Media SoC (no board model yet)

![argus2](https://i.imgur.com/CPNv0HL.jpg)

feel free to close as this not really an issue but more info if anyone decides to dig further into this model.

**Comment by user747** [comment]
also of note for the Argus 2 - the motion detection can be really janky at times. It has a [Excelitas Technology PYD 1698](https://media.digikey.com/pdf/Data%20Sheets/Excelitas%20PDFs/PYD_1688,PYD_1698.pdf) which claims 110 degree FOV. 

if one decides to open up, ensure you are very careful as there is a delicate o-ring (lubed with silicone grease) and if that stretches in the slightest amount, you will not be able to put the camera back together.

**Comment by gz7-design** [comment]
Hi @user747, I've just opened my argus 2 and I can see the space for a 5 pin connector on the board, but I am not sure if it's for a JTAG connector or a serial connector. Were you able to connect to it and see the serial port output? If so, could you share the RX, TX and GND pin locations? Many thanks!
