### ISSUE TITLE
Recompile newest IPC_51316M FW to discontinued C1-Pro

### ISSUE THREAD

**Issue by Shurov** [hn/reolink-camera#7]
I have [Reolink C1 Pro](https://reolink.com/product/c1-pro/), which is now discontinued and have latest [FW from June 2019](https://support.reolink.com/hc/en-us/articles/360025688034-06-14-2019-Firmware-for-Reolink-IP-Cameras-IPC-51316M-). However, other cameras on the **same HW** (IPC_51316M), e.g. RLC-410 have recent [December update](https://support.reolink.com/hc/en-us/articles/900004648143-12-11-2020-Firmware-for-Reolink-IP-Cameras-IPC-51316M-) that includes much needed Flash replacement as well as lots of other accumulated fixes from several firmware updates. Apparently Reolink doesn't want to compile any new firmware to the discontinued model.
Is it possible to download both firmwares - for my C1 Pro and the most recent for IPC-51316M, and recompile the latter one with the bootloader from my model? Or what else needs to be taken from my firmware? Could you help with some instructions please?

**Comment by hn** [comment]
I _might_ be possible to just exchange the HTML/CSS/JS code. Unpack both firmwares and compare differences, try to repack and flash a modified firmware. Sorry, I can only give you these generic instructions, you'll have to try for yourself.

**Comment by Shurov** [comment]
Thanks, hopefully, I'll decide(dare) to do it during NY eve

**Comment by Shurov** [comment]
UPD: they released (however, not publicly) the new firmware for C1 Pro and some other cameras: [announcement in Reddit](https://www.reddit.com/r/reolinkcam/comments/kjxy6q/firmware_update_for_part_of_reolink_cameras/)

**Comment by ristomatti** [comment]
@Shurov Thank you for the link! I would have missed the update otherwise. It seemed to bring a lot of improvements like HTML5 preview to replace the Flash player based which didn't work on mobile. 👍
