### ISSUE TITLE
Custom Watermark

### ISSUE THREAD

**Issue by hhsvision** [hn/reolink-camera#8]
Hello,

I have figured out how to extract the .pak file using the 7zip program and have access to the directories. I found the watermark files under mnt/app/ and then the 3 watermark files are listed as watermark_e.bmp, watermark_m.bmp, and watermark_s.bmp. I have created 3 of my own bmp files based on the specifications of the already existing ones and have tried to repackage the pak file in 7zip by just changing the 7z file extension to .pak, but the camera seems to be rejecting the firmware as its unable to recognize the file type it says. Any ideas on how I can get this to work? I'd also be willing to pay someone to demo this for me so I could do it myself in the future. I will attach a copy of my custom pak file, but I would say there are settings not right with how it archives it again.
[IPC_51516M5M.116_20103104.RLC-511W.OV05A10.5MP.WIFI1021.AF.REOLINK (2).zip](https://github.com/hn/reolink-camera/files/5832713/IPC_51516M5M.116_20103104.RLC-511W.OV05A10.5MP.WIFI1021.AF.REOLINK.2.zip)

**Comment by hn** [comment]
It's not possible to unpack/pack the *.pak file with 7z, you need to use a special program for that. See https://github.com/hn/reolink-camera/pull/5
